### ISSUE TITLE
Conjunction with ebl and SA 3.4.2

### ISSUE THREAD

**Issue by heutger** [smfreegard/HashBL#3]
Hi,

with SA 3.4.2 I first heard of HashBL and EBL and I‘m now confused on how to activate and try. So your plugin is seperate development? Or has it sth. to do with SA release or EBL plugin download? I ask as I dunno about how to get use of and wondering on your cf file, if it can be adopted, but I never heard of black and grey status and can’t find such information on EBL website?

Regards,
Christian

**Comment by smfreegard** [comment]
This plugin is now included in SA as of 3.4.2.  You should therefore follow the SA documentation.

With regards to BLACK .vs. GREY - I don't know if the EBL is still using this as I can't find it in their documentation either, basically they return a different code for listings (127.0.1.x) for listings that might not be 100% black, so should be scored less.

**Comment by heutger** [comment]
The documentation is https://spamassassin.apache.org/full/3.4.x/doc/Mail_SpamAssassin_Plugin_HashBL.html, I can't find anything else, and that's really rare information.
